import 'package:hive_flutter/hive_flutter.dart';
import '../../features/focus/data/models/user_model.dart';
import '../../features/focus/data/models/timer_state_model.dart';
import '../../features/focus/data/models/focus_session_model.dart';
import '../../features/onboarding/data/models/onboarding_model.dart';
import '../../features/pet/data/models/pet_model.dart';
import '../../features/pet/data/models/pet_mood_adapter.dart';
import '../../features/shop/data/models/shop_item_model.dart';
import '../../features/shop/data/models/shop_item_adapters.dart';
import '../../features/statistics/data/models/achievement_model.dart';
import '../../features/statistics/data/models/achievement_id_adapter.dart';
import '../../features/statistics/data/models/statistics_model.dart';
import '../../features/settings/data/models/settings_model.dart';
import '../../features/settings/data/models/settings_enum_adapters.dart';
import '../constants/hive_keys.dart';
import '../errors/app_exceptions.dart';

/// Service for managing Hive database operations
class HiveService {
  static const String _tag = 'HiveService';
  static bool _initialized = false;

  /// Initialize Hive and open required boxes
  static Future<void> init() async {
    try {
      if (_initialized) {
        return;
      }

      // Initialize Hive
      await Hive.initFlutter();

      // Register adapters (generated by build_runner)
      try {
        Hive.registerAdapter(OnboardingModelAdapter());
        Hive.registerAdapter(UserModelAdapter());
        Hive.registerAdapter(TimerStateModelAdapter());
        Hive.registerAdapter(FocusSessionModelAdapter());
        Hive.registerAdapter(PetModelAdapter());
        Hive.registerAdapter(PetMoodAdapter());
        Hive.registerAdapter(ShopItemModelAdapter());
        Hive.registerAdapter(ItemCategoryAdapter());
        Hive.registerAdapter(ItemRarityAdapter());
        Hive.registerAdapter(AchievementModelAdapter());
        Hive.registerAdapter(AchievementIdAdapter());
        Hive.registerAdapter(StatisticsModelAdapter());
        Hive.registerAdapter(SettingsModelAdapter());
        Hive.registerAdapter(AppThemeModeAdapter());
        Hive.registerAdapter(AmbientSoundAdapter());
        Hive.registerAdapter(BlockIntensityAdapter());
      } catch (e) {
        print('[$_tag] Warning: Adapters not yet generated by build_runner: $e');
      }

      // Open boxes
      await _openBox(HiveKeys.userBox);
      await _openBox(HiveKeys.petBox);
      await _openBox(HiveKeys.sessionBox);
      await _openBox(HiveKeys.shopBox);
      await _openBox(HiveKeys.settingsBox);
      await _openBox(HiveKeys.statisticsBox);
      await _openBox(HiveKeys.achievementsBox);
      await _openBox(HiveKeys.onboardingBox);

      _initialized = true;
      print('[$_tag] Hive initialized successfully with 7 boxes');
    } catch (e) {
      throw HiveException('Failed to initialize Hive: $e');
    }
  }

  /// Open a Hive box safely
  static Future<void> _openBox(String boxName) async {
    try {
      if (!Hive.isBoxOpen(boxName)) {
        await Hive.openBox(boxName);
      }
    } catch (e) {
      throw HiveException('Failed to open box "$boxName": $e');
    }
  }

  /// Get a specific box
  static Box<dynamic> getBox(String boxName) {
    try {
      if (!Hive.isBoxOpen(boxName)) {
        throw HiveException('Box "$boxName" is not open');
      }
      return Hive.box(boxName);
    } catch (e) {
      throw HiveException('Failed to get box "$boxName": $e');
    }
  }

  /// Write a value to a box
  static Future<void> put({
    required String boxName,
    required String key,
    required dynamic value,
  }) async {
    try {
      final box = getBox(boxName);
      await box.put(key, value);
    } catch (e) {
      throw HiveException('Failed to write to "$boxName": $e');
    }
  }

  /// Read a value from a box
  static dynamic get({
    required String boxName,
    required String key,
    dynamic defaultValue,
  }) {
    try {
      final box = getBox(boxName);
      return box.get(key, defaultValue: defaultValue);
    } catch (e) {
      throw HiveException('Failed to read from "$boxName": $e');
    }
  }

  /// Delete a value from a box
  static Future<void> delete({
    required String boxName,
    required String key,
  }) async {
    try {
      final box = getBox(boxName);
      await box.delete(key);
    } catch (e) {
      throw HiveException('Failed to delete from "$boxName": $e');
    }
  }

  /// Check if a key exists in a box
  static bool containsKey({
    required String boxName,
    required String key,
  }) {
    try {
      final box = getBox(boxName);
      return box.containsKey(key);
    } catch (e) {
      throw HiveException('Failed to check key in "$boxName": $e');
    }
  }

  /// Clear all data from a box
  static Future<void> clearBox(String boxName) async {
    try {
      final box = getBox(boxName);
      await box.clear();
    } catch (e) {
      throw HiveException('Failed to clear box "$boxName": $e');
    }
  }

  /// Clear all Hive data (reset app)
  static Future<void> clearAll() async {
    try {
      await Hive.deleteFromDisk();
      _initialized = false;
      print('[$_tag] All Hive data cleared');
    } catch (e) {
      throw HiveException('Failed to clear all Hive data: $e');
    }
  }

  /// Compact all boxes (maintenance)
  static Future<void> compactAll() async {
    try {
      final boxes = [
        HiveKeys.userBox,
        HiveKeys.petBox,
        HiveKeys.sessionBox,
        HiveKeys.shopBox,
        HiveKeys.settingsBox,
        HiveKeys.statisticsBox,
        HiveKeys.onboardingBox,
      ];

      for (final boxName in boxes) {
        if (Hive.isBoxOpen(boxName)) {
          await getBox(boxName).compact();
        }
      }
      print('[$_tag] All boxes compacted');
    } catch (e) {
      throw HiveException('Failed to compact boxes: $e');
    }
  }

  /// Cleanup
  void dispose() {
    print('[$_tag] Disposed');
  }

  // User convenience methods
  /// Get current user or null
  static UserModel? getUser() {
    try {
      final box = HiveService.getBox(HiveKeys.userBox);
      final user = box.get('currentUser');
      return user is UserModel ? user : null;
    } catch (e) {
      print('Error getting user: $e');
      return null;
    }
  }

  /// Save user
  static Future<void> saveUser(UserModel user) async {
    try {
      final box = HiveService.getBox(HiveKeys.userBox);
      await box.put('currentUser', user);
    } catch (e) {
      throw HiveException('Failed to save user: $e');
    }
  }

  /// Get or create user
  static Future<UserModel> getUserOrCreate() async {
    var user = getUser();
    if (user == null) {
      user = UserModel.defaultUser();
      await saveUser(user);
      return user;
    }

    // Migration: users created before the 500-coin starting bonus existed
    // (identifiable by zero coins and zero focus minutes — i.e. they never
    // had a chance to earn coins yet) get the bonus applied once.
    if (user.coins == 0 && user.totalFocusMinutes == 0) {
      user = user.copyWith(coins: 500);
      await saveUser(user);
    }

    return user;
  }

  // Timer convenience methods
  /// Get current timer state or null
  static TimerStateModel? getTimerState() {
    try {
      final box = HiveService.getBox(HiveKeys.sessionBox);
      final state = box.get('currentTimerState');
      return state is TimerStateModel ? state : null;
    } catch (e) {
      print('Error getting timer state: $e');
      return null;
    }
  }

  /// Save timer state
  static Future<void> saveTimerState(TimerStateModel state) async {
    try {
      final box = HiveService.getBox(HiveKeys.sessionBox);
      await box.put('currentTimerState', state);
    } catch (e) {
      throw HiveException('Failed to save timer state: $e');
    }
  }

  /// Get all focus sessions
  static List<FocusSessionModel> getAllSessions() {
    try {
      final box = HiveService.getBox(HiveKeys.sessionBox);
      final sessions = <FocusSessionModel>[];
      for (var i = 0; i < box.length; i++) {
        final key = box.keyAt(i);
        if (key.toString().startsWith('session_')) {
          final session = box.getAt(i);
          if (session is FocusSessionModel) {
            sessions.add(session);
          }
        }
      }
      return sessions;
    } catch (e) {
      print('Error getting sessions: $e');
      return [];
    }
  }

  /// Save focus session
  static Future<void> saveFocusSession(FocusSessionModel session) async {
    try {
      final box = HiveService.getBox(HiveKeys.sessionBox);
      await box.put('session_${session.id}', session);
    } catch (e) {
      throw HiveException('Failed to save focus session: $e');
    }
  }

  // Onboarding convenience methods
  /// Get onboarding state
  static OnboardingModel? getOnboarding() {
    try {
      final box = HiveService.getBox(HiveKeys.onboardingBox);
      final onboarding = box.get('onboarding');
      return onboarding is OnboardingModel ? onboarding : null;
    } catch (e) {
      print('Error getting onboarding: $e');
      return null;
    }
  }

  /// Save onboarding state
  static Future<void> saveOnboarding(OnboardingModel onboarding) async {
    try {
      final box = HiveService.getBox(HiveKeys.onboardingBox);
      await box.put('onboarding', onboarding);
    } catch (e) {
      throw HiveException('Failed to save onboarding: $e');
    }
  }

  /// Mark onboarding as completed
  static Future<void> completeOnboarding() async {
    try {
      final onboarding = OnboardingModel(
        isCompleted: true,
        completedAt: DateTime.now(),
      );
      await saveOnboarding(onboarding);
    } catch (e) {
      throw HiveException('Failed to complete onboarding: $e');
    }
  }

  /// Check if onboarding is completed
  static bool isOnboardingCompleted() {
    try {
      final onboarding = getOnboarding();
      return onboarding?.isCompleted ?? false;
    } catch (e) {
      print('Error checking onboarding: $e');
      return false;
    }
  }

  // Empty constructor to prevent instantiation
  HiveService._();
}
